// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, name, description, public)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, public, created_at, updated_at
`

type CreateCollectionParams struct {
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :one
DELETE FROM collections
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, public, created_at, updated_at
`

type DeleteCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, deleteCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, user_id, name, description, public, created_at, updated_at FROM collections
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicCollection = `-- name: GetPublicCollection :many
SELECT c.name, c.description, c.created_at, c.updated_at,
    u.display_name, u.username,
    l.id AS link_id,
    l.title AS link_title,
    l.description AS link_description,
    l.url AS link_url,
    l.created_at AS link_created_at
FROM collections c
JOIN users u ON u.id = c.user_id
LEFT JOIN links l ON l.collection_id = c.id AND l.user_id = c.user_id
WHERE c.id = $1
    AND c.public = TRUE
    AND (u.is_pro = TRUE OR u.is_admin = TRUE)
ORDER BY l.created_at DESC, l.id DESC
`

type GetPublicCollectionRow struct {
	Name            string
	Description     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DisplayName     string
	Username        string
	LinkID          *uuid.UUID
	LinkTitle       *string
	LinkDescription *string
	LinkUrl         *string
	LinkCreatedAt   *time.Time
}

func (q *Queries) GetPublicCollection(ctx context.Context, id uuid.UUID) ([]GetPublicCollectionRow, error) {
	rows, err := q.db.Query(ctx, getPublicCollection, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicCollectionRow{}
	for rows.Next() {
		var i GetPublicCollectionRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Username,
			&i.LinkID,
			&i.LinkTitle,
			&i.LinkDescription,
			&i.LinkUrl,
			&i.LinkCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.user_id, c.name, c.description, c.public, c.created_at, c.updated_at, COUNT(l.id) AS link_count
FROM collections c
    LEFT JOIN links l ON l.collection_id = c.id
WHERE c.user_id = $1
GROUP BY c.id
ORDER BY c.name
`

type ListCollectionsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LinkCount   int64
}

func (q *Queries) ListCollections(ctx context.Context, userID uuid.UUID) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $3, description = $4, public = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, public, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
