// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const clonePublicCollection = `-- name: ClonePublicCollection :one
WITH source AS (
    SELECT c.id, c.user_id, c.name, c.description, c.public, c.created_at, c.updated_at, c.slug
    FROM collections c
    JOIN users u ON u.id = c.user_id
    WHERE c.id = $1
        AND c.public = TRUE
        AND (u.is_pro = TRUE OR u.is_admin = TRUE)
), cloned AS (
    INSERT INTO collections (user_id, name, slug, description, public)
    SELECT $2, name, slug, description, FALSE
    FROM source
    WHERE user_id <> $2
    RETURNING id, user_id, name, description, public, created_at, updated_at, slug
), cloned_links AS (
    INSERT INTO links (
        user_id, collection_id, title, description, url,
        favourite, for_later, created_at
    )
    SELECT c.user_id, c.id, l.title, l.description, l.url,
        FALSE, FALSE, l.created_at
    FROM source s
    JOIN links l ON l.collection_id = s.id AND l.user_id = s.user_id
    CROSS JOIN cloned c
)
SELECT id, user_id, name, slug, description, public, created_at, updated_at, TRUE AS cloned
FROM cloned
UNION ALL
SELECT id, user_id, name, slug, description, public, created_at, updated_at, FALSE AS cloned
FROM source
WHERE user_id = $2
`

type ClonePublicCollectionParams struct {
	SourceID uuid.UUID
	UserID   uuid.UUID
}

type ClonePublicCollectionRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Slug        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Cloned      bool
}

func (q *Queries) ClonePublicCollection(ctx context.Context, arg ClonePublicCollectionParams) (ClonePublicCollectionRow, error) {
	row := q.db.QueryRow(ctx, clonePublicCollection, arg.SourceID, arg.UserID)
	var i ClonePublicCollectionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cloned,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, name, slug, description, public)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, public, created_at, updated_at, slug
`

type CreateCollectionParams struct {
	UserID      uuid.UUID
	Name        string
	Slug        string
	Description string
	Public      bool
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :one
DELETE FROM collections
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, public, created_at, updated_at, slug
`

type DeleteCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, deleteCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, user_id, name, description, public, created_at, updated_at, slug FROM collections
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const getPublicCollection = `-- name: GetPublicCollection :many
SELECT c.id, c.name, c.slug, c.description, c.created_at, c.updated_at,
    u.display_name, u.username,
    l.id AS link_id,
    l.title AS link_title,
    l.description AS link_description,
    l.url AS link_url,
    l.created_at AS link_created_at
FROM collections c
JOIN users u ON u.id = c.user_id
LEFT JOIN links l ON l.collection_id = c.id AND l.user_id = c.user_id
WHERE u.username = $1
    AND c.slug = $2
    AND c.public = TRUE
    AND (u.is_pro = TRUE OR u.is_admin = TRUE)
ORDER BY l.created_at DESC, l.id DESC
`

type GetPublicCollectionParams struct {
	Username string
	Slug     string
}

type GetPublicCollectionRow struct {
	ID              uuid.UUID
	Name            string
	Slug            string
	Description     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DisplayName     string
	Username        string
	LinkID          *uuid.UUID
	LinkTitle       *string
	LinkDescription *string
	LinkUrl         *string
	LinkCreatedAt   *time.Time
}

func (q *Queries) GetPublicCollection(ctx context.Context, arg GetPublicCollectionParams) ([]GetPublicCollectionRow, error) {
	rows, err := q.db.Query(ctx, getPublicCollection, arg.Username, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicCollectionRow{}
	for rows.Next() {
		var i GetPublicCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Username,
			&i.LinkID,
			&i.LinkTitle,
			&i.LinkDescription,
			&i.LinkUrl,
			&i.LinkCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.user_id, c.name, c.description, c.public, c.created_at, c.updated_at, c.slug, COUNT(l.id) AS link_count
FROM collections c
    LEFT JOIN links l ON l.collection_id = c.id
WHERE c.user_id = $1
GROUP BY c.id
ORDER BY c.name
`

type ListCollectionsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	Public      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Slug        string
	LinkCount   int64
}

func (q *Queries) ListCollections(ctx context.Context, userID uuid.UUID) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $3, slug = $4, description = $5, public = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, public, created_at, updated_at, slug
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Slug        string
	Description string
	Public      bool
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}
