// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    user_id, title, description, url, collection_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type CreateLinkParams struct {
	UserID       uuid.UUID
	Title        string
	Description  string
	Url          string
	CollectionID uuid.NullUUID
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.CollectionID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :one
DELETE FROM links
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type DeleteLinkParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, deleteLink, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT l.id, l.user_id, l.title, l.description, l.url, l.collection_id, l.created_at, l.updated_at, c.title AS collection_title
FROM links l
    LEFT JOIN collections c ON l.collection_id = c.id
WHERE l.id = $1 AND l.user_id = $2
LIMIT 1
`

type GetLinkParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetLinkRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Description     string
	Url             string
	CollectionID    uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionTitle pgtype.Text
}

func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (GetLinkRow, error) {
	row := q.db.QueryRow(ctx, getLink, arg.ID, arg.UserID)
	var i GetLinkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionTitle,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT l.id, l.user_id, l.title, l.description, l.url, l.collection_id, l.created_at, l.updated_at, c.title AS collection_title
FROM links l
    LEFT JOIN collections c ON l.collection_id = c.id
WHERE l.user_id = $1
ORDER BY l.created_at
`

type ListLinksRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Description     string
	Url             string
	CollectionID    uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionTitle pgtype.Text
}

func (q *Queries) ListLinks(ctx context.Context, userID uuid.UUID) ([]ListLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksRow{}
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CollectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    title = $3,
    description = $4,
    url = $5,
    collection_id = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type UpdateLinkParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Title        string
	Description  string
	Url          string
	CollectionID uuid.NullUUID
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.CollectionID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
