// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Resource struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description string
	Url         string
	Favourite   bool
	ReadLater   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description *string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                              uuid.UUID
	Email                           string
	EmailVerified                   bool
	EmailVerificationToken          uuid.NullUUID
	EmailVerificationTokenExpiresAt *time.Time
	Password                        string
	PasswordResetToken              uuid.NullUUID
	PasswordResetTokenExpiresAt     *time.Time
	Username                        string
	IsAdmin                         bool
	IsPro                           bool
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}
