// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateLinkTag(ctx context.Context, arg CreateLinkTagParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error)
	DeleteLink(ctx context.Context, arg DeleteLinkParams) (Link, error)
	DeleteLinkTags(ctx context.Context, linkID uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) (Tag, error)
	DeleteToken(ctx context.Context, arg DeleteTokenParams) error
	DeleteTokensByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error)
	GetLink(ctx context.Context, arg GetLinkParams) (GetLinkRow, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetTag(ctx context.Context, arg GetTagParams) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetTagsForLink(ctx context.Context, linkID uuid.UUID) ([]string, error)
	GetTagsForLinks(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTagsForLinksRow, error)
	GetTokenByHash(ctx context.Context, hash string) (Token, error)
	GetTokenById(ctx context.Context, arg GetTokenByIdParams) (Token, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailVerificationToken(ctx context.Context, emailVerificationToken uuid.NullUUID) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPasswordResetToken(ctx context.Context, passwordResetToken uuid.NullUUID) (User, error)
	ListCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error)
	ListLinks(ctx context.Context, userID uuid.UUID) ([]ListLinksRow, error)
	ListTags(ctx context.Context, userID uuid.UUID) ([]Tag, error)
	ListTokensByUserID(ctx context.Context, userID uuid.UUID) ([]Token, error)
	ListUsers(ctx context.Context) ([]User, error)
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (User, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdatePasswordResetToken(ctx context.Context, arg UpdatePasswordResetTokenParams) (User, error)
	UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (Session, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTokenLastUsedAt(ctx context.Context, id uuid.UUID) error
	UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
	VerifyUser(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
