// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteResource(ctx context.Context, arg DeleteResourceParams) (Resource, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	GetResource(ctx context.Context, arg GetResourceParams) (Resource, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailVerificationToken(ctx context.Context, emailVerificationToken uuid.NullUUID) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPasswordResetToken(ctx context.Context, passwordResetToken uuid.NullUUID) (User, error)
	ListResources(ctx context.Context, userID uuid.UUID) ([]Resource, error)
	ListUsers(ctx context.Context) ([]User, error)
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (User, error)
	UpdatePasswordResetToken(ctx context.Context, arg UpdatePasswordResetTokenParams) (User, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (Session, error)
	UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error)
	VerifyUser(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
