// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title, url
) VALUES (
  $1, $2
)
RETURNING id, title, url
`

type CreateResourceParams struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource, arg.Title, arg.Url)
	var i Resource
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, url FROM resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResource(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, title, url FROM resources
ORDER BY title
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(&i.ID, &i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
  set title = $2,
  url = $3
WHERE id = $1
RETURNING id, title, url
`

type UpdateResourceParams struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource, arg.ID, arg.Title, arg.Url)
	var i Resource
	err := row.Scan(&i.ID, &i.Title, &i.Url)
	return i, err
}
