// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    user_id, title, description, url, favourite, read_later
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, title, description, url, favourite, read_later, created_at, updated_at
`

type CreateResourceParams struct {
	UserID      uuid.UUID
	Title       string
	Description string
	Url         string
	Favourite   bool
	ReadLater   bool
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Favourite,
		arg.ReadLater,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = $1 AND user_id = $2
`

type DeleteResourceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteResource, arg.ID, arg.UserID)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, user_id, title, description, url, favourite, read_later, created_at, updated_at FROM resources
WHERE
    id = $1 AND user_id = $2
LIMIT 1
`

type GetResourceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, arg.ID, arg.UserID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, user_id, title, description, url, favourite, read_later, created_at, updated_at FROM resources
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListResources(ctx context.Context, userID uuid.UUID) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.Favourite,
			&i.ReadLater,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
    title = $3,
    description = $4,
    url = $5,
    favourite = $6,
    read_later = $7
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, favourite, read_later, created_at, updated_at
`

type UpdateResourceParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description string
	Url         string
	Favourite   bool
	ReadLater   bool
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Favourite,
		arg.ReadLater,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
