// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title, description, url, favourite, read_later
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, title, description, url, favourite, read_later, created_at, updated_at
`

type CreateResourceParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Url         string `json:"url"`
	Favourite   bool   `json:"favourite"`
	ReadLater   bool   `json:"readLater"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Favourite,
		arg.ReadLater,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, description, url, favourite, read_later, created_at, updated_at FROM resources
WHERE id =
$1 LIMIT 1
`

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, title, description, url, favourite, read_later, created_at, updated_at FROM resources
ORDER BY created_at
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.Favourite,
			&i.ReadLater,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
  SET title = $2,
  description = $3,
  url = $4,
  favourite = $5,
  read_later = $6
WHERE id = $1
RETURNING id, title, description, url, favourite, read_later, created_at, updated_at
`

type UpdateResourceParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Url         string    `json:"url"`
	Favourite   bool      `json:"favourite"`
	ReadLater   bool      `json:"readLater"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Favourite,
		arg.ReadLater,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Favourite,
		&i.ReadLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
