// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_hash, description, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, session_hash, description, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID
	SessionHash string
	Description *string
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionHash,
		arg.Description,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions
WHERE session_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, sessionHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, sessionHash)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE id = $1 AND user_id = $2
`

type DeleteSessionByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, arg.ID, arg.UserID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, session_hash, description, expires_at, created_at, updated_at FROM sessions
WHERE session_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, sessionHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, sessionHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, session_hash, description, expires_at, created_at, updated_at FROM sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionHash,
			&i.Description,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionExpiresAt = `-- name: UpdateSessionExpiresAt :one
UPDATE sessions
SET expires_at = $2
WHERE id = $1
RETURNING id, user_id, session_hash, description, expires_at, created_at, updated_at
`

type UpdateSessionExpiresAtParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionExpiresAt, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
