// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, description, hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, description, hash, last_used_at, created_at, updated_at
`

type CreateTokenParams struct {
	UserID      uuid.UUID
	Description string
	Hash        string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.UserID, arg.Description, arg.Hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Hash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens
WHERE id = $1 AND user_id = $2
`

type DeleteTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteToken, arg.ID, arg.UserID)
	return err
}

const deleteTokensByUserID = `-- name: DeleteTokensByUserID :exec
DELETE FROM tokens
WHERE user_id = $1
`

func (q *Queries) DeleteTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUserID, userID)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, description, hash, last_used_at, created_at, updated_at FROM tokens
WHERE hash = $1
LIMIT 1
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Hash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenById = `-- name: GetTokenById :one
SELECT id, user_id, description, hash, last_used_at, created_at, updated_at FROM tokens
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTokenByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTokenById(ctx context.Context, arg GetTokenByIdParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenById, arg.ID, arg.UserID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Hash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTokensByUserID = `-- name: ListTokensByUserID :many
SELECT id, user_id, description, hash, last_used_at, created_at, updated_at FROM tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByUserID(ctx context.Context, userID uuid.UUID) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Hash,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenLastUsedAt = `-- name: UpdateTokenLastUsedAt :exec
UPDATE tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateTokenLastUsedAt, id)
	return err
}
