// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, type, description, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, description, expires_at, created_at, updated_at
`

type CreateTokenParams struct {
	UserID      uuid.UUID
	Type        string
	Description *string
	ExpiresAt   time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.UserID,
		arg.Type,
		arg.Description,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenById = `-- name: GetTokenById :one
SELECT id, user_id, type, description, expires_at, created_at, updated_at FROM tokens
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTokenById(ctx context.Context, id uuid.UUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenById, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTokenExpiresAt = `-- name: UpdateTokenExpiresAt :one
UPDATE tokens
SET expires_at = $2
WHERE id = $1
RETURNING id, user_id, type, description, expires_at, created_at, updated_at
`

type UpdateTokenExpiresAtParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) UpdateTokenExpiresAt(ctx context.Context, arg UpdateTokenExpiresAtParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, updateTokenExpiresAt, arg.ID, arg.ExpiresAt)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens
WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}
