// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    email_verified,
    email_verification_token,
    email_verification_token_expires_at,
    password,
    username,
    is_admin,
    is_pro
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at
`

type CreateUserParams struct {
	Email                           string
	EmailVerified                   bool
	EmailVerificationToken          uuid.NullUUID
	EmailVerificationTokenExpiresAt *time.Time
	Password                        string
	Username                        string
	IsAdmin                         bool
	IsPro                           bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.EmailVerificationToken,
		arg.EmailVerificationTokenExpiresAt,
		arg.Password,
		arg.Username,
		arg.IsAdmin,
		arg.IsPro,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at FROM users
WHERE
    email
    =
    $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailVerificationToken = `-- name: GetUserByEmailVerificationToken :one
SELECT id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at FROM users
WHERE
    email_verification_token
    =
    $1
LIMIT 1
`

func (q *Queries) GetUserByEmailVerificationToken(ctx context.Context, emailVerificationToken uuid.NullUUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailVerificationToken, emailVerificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at FROM users
WHERE
    id
    =
    $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerificationToken,
			&i.EmailVerificationTokenExpiresAt,
			&i.Password,
			&i.Username,
			&i.IsAdmin,
			&i.IsPro,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVerificationToken = `-- name: UpdateVerificationToken :one
UPDATE users
SET
    email_verification_token = $2,
    email_verification_token_expires_at = $3
WHERE id = $1
RETURNING id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at
`

type UpdateVerificationTokenParams struct {
	ID                              uuid.UUID
	EmailVerificationToken          uuid.NullUUID
	EmailVerificationTokenExpiresAt *time.Time
}

func (q *Queries) UpdateVerificationToken(ctx context.Context, arg UpdateVerificationTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateVerificationToken, arg.ID, arg.EmailVerificationToken, arg.EmailVerificationTokenExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET
    email_verified = TRUE,
    email_verification_token = NULL,
    email_verification_token_expires_at = NULL
WHERE id = $1
RETURNING id, email, email_verified, email_verification_token, email_verification_token_expires_at, password, username, is_admin, is_pro, created_at, updated_at
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiresAt,
		&i.Password,
		&i.Username,
		&i.IsAdmin,
		&i.IsPro,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
